services:
  auth_micro_service_backend_test:
    build:
      context: ./
      dockerfile: tools/docker/auth.Dockerfile
    depends_on:
      - migration_test
    environment:
      - SQL_DSN=postgresql://root:root@auth_micro_service_db_test:5430/auth_micro_service?sslmode=disable
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
    expose:
      - 3000
    
  migration_test:
    build:
      context: ./
      dockerfile: tools/docker/migration.Dockerfile
    environment:
      - SQL_DSN=postgresql://root:root@auth_micro_service_db_test:5430/auth_micro_service?sslmode=disable
    depends_on:
      auth_micro_service_db_test:
        condition: service_healthy
    networks:
      - backend

  auth_micro_service_db_test:
    image: postgres:12-alpine
    restart: always
    environment:
      - PGPORT=5430 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGUSER=root
      - POSTGRES_DB=auth_micro_service
    ports:
      - 5430:5430
    expose:
      - 5430
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  auth_micro_service_proxy_test:
    build:
      context: ./
      dockerfile: tools/docker/nginx_test.Dockerfile
    depends_on:
      - auth_micro_service_backend_test
    networks:
      - frontend
    ports:
      - 80:80
    expose:
      - 80
  
networks:
  frontend:
  backend:
