CREATE TABLE "person" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "personname" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "title" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "title_person" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" integer,
  "title_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "person" ("id", "personname", "email");

CREATE INDEX ON "title" ("id");

ALTER TABLE "title_person" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("id");

ALTER TABLE "title_person" ADD FOREIGN KEY ("title_id") REFERENCES "title" ("id");
